### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by benbox69** [Rihan9/LD2412#14]
Good day,

I am quite new in the ESP home and try to use your code with my LD2412 but I have this message when I try to compile the code :

```
INFO ESPHome 2024.10.2
INFO Reading configuration /config/esphome/master-suite--environment-sensor.yaml...
WARNING GPIO2 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing environment-sensor (board: esp32dev; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.4
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.2.2
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/environment-sensor/src/esphome/components/LD2412/LD2412.cpp.o
Compiling .pioenvs/environment-sensor/src/esphome/components/api/api_frame_helper.cpp.o
src/esphome/components/LD2412/LD2412.cpp: In member function 'bool esphome::LD2412::LD2412Component::handle_ack_data_(uint8_t*, int)':
src/esphome/components/LD2412/LD2412.cpp:471:15: error: 'class esphome::LD2412::LD2412Component' has no member named 'mode_select_'
         this->mode_select_->publish_state("Dynamic background correction");
               ^~~~~~~~~~~~
src/esphome/components/LD2412/LD2412.cpp:473:15: error: 'class esphome::LD2412::LD2412Component' has no member named 'mode_select_'
         this->mode_select_->publish_state("Normal");
               ^~~~~~~~~~~~
src/esphome/components/LD2412/LD2412.cpp:494:32: error: 'class esphome::LD2412::LD2412Component' has no member named 'gate_still_threshold_numbers_'; did you mean 'gate_still_sensors_'?
       for(int i = 0; i < this->gate_still_threshold_numbers_.size(); i++){
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                gate_still_sensors_
src/esphome/components/LD2412/LD2412.cpp:495:50: error: 'class esphome::LD2412::LD2412Component' has no member named 'gate_move_threshold_numbers_'; did you mean 'gate_move_sensors_'?
         updates.push_back(set_number_value(this->gate_move_threshold_numbers_[i], buffer[10+i]));
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  gate_move_sensors_
src/esphome/components/LD2412/LD2412.cpp:495:27: error: 'set_number_value' was not declared in this scope
         updates.push_back(set_number_value(this->gate_move_threshold_numbers_[i], buffer[10+i]));
                           ^~~~~~~~~~~~~~~~
src/esphome/components/LD2412/LD2412.cpp:495:27: note: suggested alternative: 'set_interval'
         updates.push_back(set_number_value(this->gate_move_threshold_numbers_[i], buffer[10+i]));
                           ^~~~~~~~~~~~~~~~
                           set_interval
src/esphome/components/LD2412/LD2412.cpp:504:32: error: 'class esphome::LD2412::LD2412Component' has no member named 'gate_still_threshold_numbers_'; did you mean 'gate_still_sensors_'?
       for(int i = 0; i < this->gate_still_threshold_numbers_.size(); i++){
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                gate_still_sensors_
src/esphome/components/LD2412/LD2412.cpp:505:50: error: 'class esphome::LD2412::LD2412Component' has no member named 'gate_still_threshold_numbers_'; did you mean 'gate_still_sensors_'?
         updates.push_back(set_number_value(this->gate_still_threshold_numbers_[i], buffer[10+i]));
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  gate_still_sensors_
src/esphome/components/LD2412/LD2412.cpp:505:27: error: 'set_number_value' was not declared in this scope
         updates.push_back(set_number_value(this->gate_still_threshold_numbers_[i], buffer[10+i]));
                           ^~~~~~~~~~~~~~~~
src/esphome/components/LD2412/LD2412.cpp:505:27: note: suggested alternative: 'set_interval'
         updates.push_back(set_number_value(this->gate_still_threshold_numbers_[i], buffer[10+i]));
                           ^~~~~~~~~~~~~~~~
                           set_interval
*** [.pioenvs/environment-sensor/src/esphome/components/LD2412/LD2412.cpp.o] Error 1
========================== [FAILED] Took 8.08 seconds ==========================
```
Here is my YAML code:

```
external_components:
  - source:
      type: git
      url: https://github.com/Rihan9/LD2412
      ref: main
    components: [LD2412]

esphome:
  name: environment-sensor
  friendly_name: THPM sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "secret"

ota:
  - platform: esphome
    password: "scret"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "THMPS Fallback Hotspot"
    password: ""

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200
  parity: NONE
  stop_bits: 1

LD2412:
  id: ld2412
  throttle: 3s

sensor:
  - platform: dht
    pin: GPIO2
    model: DHT22
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Motion"
    device_class: motion
  - platform: LD2412
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
```

Can you help me with this issue ?

BR

**Comment by Rihan9** [comment]
Hi!
you found quite an amazing bug. the workaround is to add ALL the entities in the example. I'll work on this to make sure if an entity is not added, the code does not try to set it

**Comment by Rihan9** [comment]
Nevermind, I fix it in the dev branch. Can you please check on it? on the external_components change refs to Dev and try to recompile it. probably, you will need to clean the build files. Try without doing it, and if the compiler rise an error, retry after clean them

**Comment by benbox69** [comment]
> Nevermind, I fix it in the dev branch. Can you please check on it? on the external_components change refs to Dev and try to recompile it. probably, you will need to clean the build files. Try without doing it, and if the compiler rise an error, retry after clean them

Cleaned build files and tried this way: 
```
external_components:
  - source:
      type: git
      url: https://github.com/Rihan9/LD2412
      ref: dev
    components: [LD2412]
```
But I still have the same error messages

**Comment by benbox69** [comment]
> Hi! you found quite an amazing bug. the workaround is to add ALL the entities in the example. I'll work on this to make sure if an entity is not added, the code does not try to set it

This solved the problem

**Comment by Rihan9** [comment]
Yeah but is not a solution, is a workaround ;)

**Comment by benbox69** [comment]
Sure but at least I can test the LD2412 sensor. I understood that you are quite busy, so I will be waiting for the fixed version and use this workaround for now.

Thanks for your work!

**Comment by Rihan9** [comment]
Thanks!

**Comment by Rihan9** [comment]
Hi @benbox69,
I was losing my mind trying to understand why the local exteternal repository worked ok, but with the github source mentioned above not.

The correct import is:
```
external_components:
  - source:
      type: git
      url: https://github.com/Rihan9/LD2412
      ref: Dev
    components: [LD2412]
```

Can you see the difference? yah, that's right. The D for the ref is in uppercase. Can you try and confirm that works?

**Comment by benbox69** [comment]
Hi @Rihan9 ,

made the change and tried to remove the select in the YAML and got this message:

```
src/esphome/components/LD2412/LD2412.cpp: In member function 'void esphome::LD2412::LD2412Component::set_basic_config()':
src/esphome/components/LD2412/LD2412.cpp:726:14: error: 'class esphome::LD2412::LD2412Component' has no member named 'out_pin_level_select_'; did you mean 'out_pin_level_'?
       !this->out_pin_level_select_->has_state()) {
              ^~~~~~~~~~~~~~~~~~~~~
              out_pin_level_
src/esphome/components/LD2412/LD2412.cpp:734:40: error: 'class esphome::LD2412::LD2412Component' has no member named 'out_pin_level_select_'; did you mean 'out_pin_level_'?
     OUT_PIN_LEVEL_ENUM_TO_INT.at(this->out_pin_level_select_->state)
                                        ^~~~~~~~~~~~~~~~~~~~~
                                        out_pin_level_
*** [.pioenvs/environment-sensor/src/esphome/components/LD2412/LD2412.cpp.o] Error 1
```

When removing the sensor:

```
src/esphome/components/LD2412/select/light_out_control_select.cpp: In member function 'virtual void esphome::LD2412::LightOutControlSelect::control(const string&)':
src/esphome/components/LD2412/select/light_out_control_select.cpp:8:18: error: 'class esphome::LD2412::LD2412Component' has no member named 'set_basic_config'
   this->parent_->set_basic_config();
                  ^~~~~~~~~~~~~~~~
*** [.pioenvs/environment-sensor/src/esphome/components/LD2412/select/light_out_control_select.cpp.o] Error 1
```

**Comment by Rihan9** [comment]
Hi,
I don't know what tell you. My configuration works just fine. I'll post below the entire configuration without any cut,  try to see if you find any difference with yours. 

P.S. please consider to clean your build files before try any changes for this issue. Any cache in this case will probably invalidate your test.

```
esphome:
  name: esp32c3-test
  friendly_name: Esp32-C3 Test
  platformio_options:
    board_build.f_cpu: 80000000L

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
    version: recommended

external_components:
  - source:
      type: git
      url: https://github.com/Rihan9/LD2412
      ref: Dev
    components: [LD2412]

# Enable logging
logger:
  level: VERY_VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "**OMITTED**"

# mqtt:
#   broker: !secret mqtt_addr
#   username: !secret mqtt_user
#   password: !secret mqtt_password
ota:
  - platform: esphome
    password: "**OMITTED**"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 13dB
#  enable_btm: True
#  enable_rrm: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C3-Test Fallback Hotspot"
    password: "**OMITTED**"

captive_portal:

uart:
  id: uart_bus
  rx_pin: 
    number: GPIO02
    mode:
      input: true
      pullup: true
  tx_pin: 
    number: GPIO01
    mode:
      input: true
      pullup: true
  baud_rate: 115200
  parity: NONE
i2c:
  sda: GPIO10
  scl: GPIO09
  scan: false
  id: bus_a

LD2412:
  id: ld2412
  throttle: 3s

binary_sensor:
  - platform: LD2412
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
```
